
---
- hosts: localhost
  vars:
    aggrname: aggr1
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  gather_facts: false
  collections:
    - netapp.ontap
  tasks:
  - name: Get Ontap Info
    na_ontap_info:
      state: info
      gather_subset:
        - cluster_identity_info
