- hosts: localhost
  name: ONTAP
  gather_facts: false
  vars:
    hostname: "1.1.1.1"
    volname: ansibleVolume
    vserver: ansible_vserver
    aggrname:
    size: 10
    aggr: aggr1
    e_policy: 
    qos_policy:
    export_policy:
    countvol: 1
    state: present
  tasks:
  - name: "{{ tower_job_template_name }}"
    netapp.ontap.na_ontap_volume:
      state: "{{ state }}"
      name: "{{item}}"
      aggregate_name: "{{ aggr_name }}"
      size: "{{ size }}"
      size_unit: gb
      policy: "default"
      junction_path: "/{{ item }}"
      space_guarantee: "volume"
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      efficiency_policy: "{{ e_policy }}"
      qos_policy_group: "{{ qos_policy }}"
    with_sequence: start=1 end={{countvol|int}} format={{volname}}%02x
