---
- hosts: localhost
  gather_facts: false
  vars:
    aggrname: aggr1
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    state: present
  name: Onboard SVM
  tasks:
  - name: Create interface
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: "{{ vserver }}_mgmt_data_1"
      home_port: e0c
      home_node: fabianb-wdf-k8sstore-01
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: mgmt
      is_auto_revert: true
      address: "{{dataipaddress }}"
      netmask: 255.255.254.0
      vserver: "{{ vserver }}"
      <<: *login
  - name: create route
    netapp.ontap.na_ontap_net_routes:
      state: present
      vserver: "{{ vserver }}"
      destination: 0.0.0.0/0
      gateway: "{{ gw }}"
      metric: 30
      <<: *login
