---
- hosts: localhost
  gather_facts: false
  vars:
    aggrname: aggr1
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      state: present
  name: Onboard SVM
  tasks:
  - name: "Create or delete SVM"
    na_ontap_svm:
      state: "{{ state }}"
      name: "{{ vserver }}"
      root_volume: "{{ vserver}}_root"
      root_volume_aggregate: "{{ aggrname }}"
      root_volume_security_style: unix
      <<: *login
