---
- hosts: localhost
  gather_facts: false
  vars:
    aggrname: aggr1
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    state: present
  tasks:
  - name: Add licenses
    na_ontap_license:
      state: "{{ state }}"
      serial_number: "4082368511"
      license_codes: CODE1,CODE2
      <<: *login